name:         periodic_table
version:      0.1.2
author:       Herman Bergwerf <hermanbergwerf@gmail.com>
description:  The Periodic Table of Elements data as Dart package
homepage:     https://github.com/bergwerf/periodic-table
environment:
  sdk:        '>=2.13.4 <3.0.0'
