name:         periodic_table
version:      0.2.0
author:       Herman Bergwerf <post@hbergwerf.nl>
description:  The Periodic Table of Elements data as Dart package
homepage:     https://github.com/bergwerf/periodic_table
environment:
  sdk:        '>=2.13.4 <3.0.0'
